# config.toml

[server]
auth = ["a_ulrich@utb.cz", "EcCNVU/dS76jpE938WxRHRGmjRM="]
url = "https://intern.smart.ariscat.com/datasnap/rest/TARSMethods/GetRecordLst"
posturl = "https://intern.smart.ariscat.com/datasnap/rest/TARSMethods/RecordLst"

daystostrip = 5000
date_to = "2022-08-30" # false or "2023-01-20"

deviceIdLst = 3
apiDataIndentifier = "iot_device_data"

[args]
idColumnName = "@ID"
averageColumnName = "@iDevdAverageCurrent"
timeColumnName = "@dDevdCasZpravy"
modelPath = "models/newmodel.pckl"
# only for train.py
newModelName = "newmodel"

# args for AI algorithms, see README for info
[AI]
# training - anomalies
contamination = 0.02
# running - clusters
eps = 3
min_samples = 2

